name: build-and-publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: src/HybridRecs.Plugin
        run: dotnet restore

      - name: Build
        working-directory: src/HybridRecs.Plugin
        run: dotnet publish -c Release -o out

      - name: Package plugin zip
        run: |
          mkdir -p dist
          ZIPNAME="hybridrecs-plugin_${{ github.ref_name }}.zip"
          cp src/HybridRecs.Plugin/manifest.json src/HybridRecs.Plugin/out/manifest.json
          cd src/HybridRecs.Plugin/out
          zip -r "../../../dist/$ZIPNAME" .
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV

      - name: Compute checksum
        run: |
          cd dist
          md5sum "$ZIPNAME" | awk '{print $1}' > checksum.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            dist/${{ env.ZIPNAME }}
            dist/checksum.txt

      - name: Publish manifest to gh-pages
        run: |
          git fetch origin gh-pages || true
          git checkout -B gh-pages
          mkdir -p repo
          cp repo/manifest.json repo/manifest.json 2>/dev/null || true

          ZIPURL="https://github.com/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF_NAME}/${ZIPNAME}"
          SUM=$(cat dist/checksum.txt)

          python3 - <<'PY'
import json, os
from datetime import datetime, timezone

p = "repo/manifest.json"
with open(p) as f:
    data = json.load(f)

vers = data["plugins"][0]["versions"][0]
vers["version"] = os.environ.get("GITHUB_REF_NAME","v0.0.0").lstrip("v")
vers["sourceUrl"] = os.environ["ZIPURL"]
vers["checksum"] = open("dist/checksum.txt").read().strip()
vers["timestamp"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

with open(p,"w") as f:
    json.dump(data, f, indent=2)
PY

          git add repo/manifest.json
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "Update manifest for ${GITHUB_REF_NAME}" || true
          git push -f origin gh-pages

