name: build-and-publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        working-directory: src/HybridRecs.Plugin
        run: dotnet restore

      - name: Build
        working-directory: src/HybridRecs.Plugin
        run: dotnet build -c Release

      - name: Package plugin zip
        run: |
          mkdir -p dist
          ZIPNAME="hybridrecs-plugin_${{ github.ref_name }}.zip"
          # collect output dlls (assuming default path)
          OUTDIR=$(echo src/HybridRecs.Plugin/bin/Release/*/publish | awk '{print $1}')
          if [ -z "$OUTDIR" ]; then OUTDIR=$(echo src/HybridRecs.Plugin/bin/Release/* | awk '{print $1}'); fi
          cp src/HybridRecs.Plugin/manifest.json "$OUTDIR/manifest.json"
          cd "$OUTDIR"
          zip -r "../../../dist/$ZIPNAME" .
          echo "ZIPNAME=$ZIPNAME" >> $GITHUB_ENV

      - name: Compute checksum
        run: |
          cd dist
          md5sum "$ZIPNAME" | awk '{print $1}' > checksum.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: true
          files: |
            dist/${ env.ZIPNAME }
            dist/checksum.txt

      - name: Publish manifest to gh-pages
        run: |
          git fetch origin gh-pages || true
          git checkout -B gh-pages
          mkdir -p repo
          cp -f repo/manifest.json repo/manifest.json 2>/dev/null || true
          # Patch manifest with correct URL and checksum
          ZIPURL="https://github.com/${ github.repository }/releases/download/${ github.ref_name }/${ env.ZIPNAME }"
          SUM=$(cat dist/checksum.txt)
          python - <<'PY'
import json, os
p="repo/manifest.json"
with open(p) as f:
    data=json.load(f)
# update plugin version entry
vers=data["plugins"][0]["versions"][0]
vers["version"]=os.environ.get("GITHUB_REF_NAME","v0.0.0").lstrip("v")
vers["sourceUrl"]=os.environ["ZIPURL"]
vers["checksum"]=open("dist/checksum.txt").read().strip()
from datetime import datetime, timezone
vers["timestamp"]=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
with open(p,"w") as f:
    json.dump(data,f,indent=2)
PY
          git add repo/manifest.json
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "Update manifest for ${ github.ref_name }"
          git push -f origin gh-pages